# Generated by Django 5.0.1 on 2024-02-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('first_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('opening_time', models.DateField()),
                ('closing_time', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('advancement', models.IntegerField()),
                ('difficulty', models.CharField(max_length=15)),
                ('progression', models.CharField(max_length=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.students')),
            ],
        ),
    ]
