# Generated by Django 5.0.1 on 2024-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
