# Generated by Django 5.0.1 on 2024-02-04 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
