# Generated by Django 5.0.1 on 2024-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_alter_students_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='opening_time',
            field=models.DateTimeField(),
        ),
    ]
