# Generated by Django 5.0.1 on 2024-02-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_alter_poll_closing_time_alter_poll_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('advancement', models.IntegerField()),
                ('difficulty', models.CharField(max_length=15)),
                ('progression', models.CharField(max_length=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.students')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.polls')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.students')),
            ],
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
