# Generated by Django 5.0.1 on 2024-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_alter_students_email_polls_sessions_delete_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='polls',
            name='poll_id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polls',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False),
        ),
    ]
