# Generated by Django 5.0.1 on 2024-02-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0007_remove_polls_status_alter_polls_advancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='poll_id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
