# Generated by Django 5.0.1 on 2024-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0008_alter_polls_poll_id_alter_sessions_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='advancement',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
