# Generated by Django 5.0.1 on 2024-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0009_alter_polls_advancement_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='advancement',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
