# Generated by Django 5.0.1 on 2024-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0010_alter_polls_advancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='polls',
            name='advancement',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
