# Generated by Django 5.0.1 on 2024-02-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0011_remove_sessions_opening_time_alter_polls_advancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='opening_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
