# Generated by Django 5.0.1 on 2024-02-05 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0012_sessions_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='closing_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
