# Generated by Django 5.0.1 on 2024-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0013_alter_sessions_closing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
